libs:
  - name: movies
    path: /media/movies
  - name: anime
    path: /media/anime
    recursive: true
video_extensions:
  - '.mp4'
  - '.mkv'
  - '.avi'
  - '.m4v'
  - '.mpeg'
  - '.mpg'
  - '.mov'